export enum ROUTES {
  HOME = '/',
  LOGIN = '/login',
  REGISTER = '/register',
  SHOP = '/shop',
  PRODUCT = '/product/:id',
  CART = '/cart',
  CHECKOUT = '/checkout',
  ORDER = '/order',
  PROFILE = '/profile',
  CONTACT = '/contact',
  FORGOT_PASSWORD = '/forgot-password',
  OTP_PAGE = '/otp',
  ERROR_PAGE = '/error',
}